### ISSUE TITLE
touch: cannot touch '.command.trace': Permission denied

### ISSUE THREAD

**Issue by sjackman** [assemblerflow/flowcraft#142]
I'm seeing this error `touch: cannot touch '.command.trace': Permission denied` when running the following simple pipeline.
```sh
flowcraft build -t spades -o spades.nf
nextflow run spades.nf --fastq='sample_{1,2}.fq.gz' -profile docker
```
In what working directory is it trying to touch this file?

**Comment by tiagofilipe12** [comment]
Hi @sjackman ,

You need the quotes in the modules flag `-t`.

You should build like this:
```
flowcraft build -t "spades" -o spades.nf
```

**Comment by sjackman** [comment]
I see the same error with quotes around `"spades"`.

**Comment by sjackman** [comment]
```

**Comment by sjackman** [comment]
Singularity worked for me! I'd be curious to know why Docker is not working, but I'm happy that Singularity is working!
```sh
flowcraft build -t spades -o spades.nf
nextflow run spades.nf --fastq='sample_{1,2}.fq.gz' -profile standard
```

**Comment by ODiogoSilva** [comment]
Hi Saun. I was going to ask exactly that, if singularity runs for you. Do you have permissions to executed docker on that machine without specifying sudo? That is, have you added your user to the docker group? 

https://docs.docker.com/install/linux/linux-postinstall/

**Comment by sjackman** [comment]
Yep, Docker works on this machine.

```
$ docker run --rm hello-world | head -n2

Hello from Docker!
```

Do you know in what directory inside Docker it's trying to write this `.command.trace` trace file?

**Comment by ODiogoSilva** [comment]
Ok thanks, but it seems like a user permission error. Can  you try adding 

```
docker.runOptions = '-u $(id -u):$(id -g)'
```

to your nextflow.config file? (Check here for similar issue: https://groups.google.com/forum/#!msg/nextflow/sZEhsc4HbOQ/maMD1hf5AQAJ)

In any case, `.command.trace` is file automatically generated by nextflow on each work sub directory where the processes are executed. It is meant to store trace information (cpus, memory, time, etc)

**Comment by sjackman** [comment]
Success! That fixed it! Thanks, Diogo. This fix wasn't need on my macOS laptop, but it was needed at work on an HPC machine. Should `docker.runOptions = '-u $(id -u):$(id -g)'` be the default?

**Comment by ODiogoSilva** [comment]
I've tested this option on multiple machines that could executed docker containers previously and there was no negative impact of it. I've added this option as a default (see https://github.com/assemblerflow/flowcraft/pull/143)

**Comment by phillip-richmond-umoja** [comment]
I used this fix for the exact same error while using the ensembl-vep container. This docker flag is very useful!

**Comment by gitanoqevaporelmundoentero** [comment]
I've also used the fix when running sarek pipeline. The mentioned fix doesn't look to be a default when using docker.
