### ISSUE TITLE
Consider renaming this project or breaking into 2 project

### ISSUE THREAD

**Issue by tseemann** [assemblerflow/flowcraft#43]
I've just noticed its called `assemblerflow` and says `A NextFlow pipeline assembler for bacterial genomics` but it does a lot more than assemble genomes.

See also #42 about supporting contigs too.  The goal of this project is to use the assemblies for AMR, Virulome, cgMLST etc (ie. replace Nullarbor)

If it's not, maybe separate into assembly, and then the other genotyping?

**Comment by ODiogoSilva** [comment]
Hi Torsteen,

Assemblerflow is still in early development and unfortunately, we didn't have time to write an actual README, user-guide, tutorials, etc ([but we do have extensive API and devel documentation](http://assemblerflow.readthedocs.io/en/master/?badge=master)). However, we are developing this project as an assembler of nextflow pipelines, which may not be related with genome assembly. We did start with our genome assembly pipeline, INNuca, but we have added many other modules after that for annotation, typing and allele calling. For instance, @tiagofilipe12 is currently adding modules for the detection of plasmids from HTS data, which will use existing modules for assembly and mapping and new ones that use MASH.

Ultimately, the premise is simple. To have an array of modules (fastqc, spades, abricate, mash etc) in nextflow and allow users to build their own custom lego-like pipelines according to their needs. assemblerflow will then tie them up and output a ready to use nextflow pipeline. We also have a recipe system that generates some "curated" pipelines with particular aims, like `innuendo` for bacerial genome assembly and `patlasflow` for plasmid discovery. These modules can also produce report data that can be feed to an [interactive report aggregate](https://github.com/ODiogoSilva/report-nf) that we are working on.

I see that the name may me misleading towards genome assembly, but it's actually directed for pipeline assembly. We'll have to work on the README's and company soon, to better convey the goal and usage of the tool.

**Comment by tseemann** [comment]
So the word `assembler` doesn't mean "genome assembly", it means "to build" (*construir* ?)

**Comment by ODiogoSilva** [comment]
Yes, that's correct. But in truth the name came from avengers, assemble...

**Comment by ODiogoSilva** [comment]
Closing, as the project has been finally renamed to flowcraft.
