### ISSUE TITLE
Report JSON spec

### ISSUE THREAD

**Issue by ODiogoSilva** [assemblerflow/flowcraft#96]
As part of the upcoming Reports web app update, the report JSON object will need some refactoring from the initial implementation. This refactoring is important particularly for components that collect and report data from multiple samples simultaneously (something that the initial implementation didn't handle).

## The root

```
finalJson = {
    "processId": "1_1",
    "pipelineId": "",
    "projectid": "",
    "userId": "",
    "username": "",
    "processName": "integrity_coverage",
    "workdir": "path/to/work/dir",
    "reportJson": {(...)}
}
```

The main keys of the root object are `processId`,  `processName` and `workdir`. The remaining can be used for metadata in more specific platform instances.

### Table data

For single samples in the same component:

```
    "reportJson": {

        "tableRow": [{
            "sample": "strainA",
            "data": [{
                "header": "Raw BP",
                "value": 123,
                "table": "qc",
            }, {
                "header": "Coverage",
                "value": 32,
                "table": "qc"
            }],
            "sample": "strainB",
            "data": [{
                "header": "Raw BP",
                "value": 321,
                "table": "qc",
            }, {
                "header": "Coverage",
                "value": 22,
                "table": "qc"
            }]
        }],
   }
```

The `tableRow` signature indicates that the contents are table data. It should be an array of objects, where each object contains the `sample` key, and it's corresponding `data`. This allows the same component to include table data from multiple samples, and multiple columns for each sample.

### Plot data

Data for plots follows the same structure of the table data:

EDIT: Simplified plotData data object

```
    "reportJson": {

        "plotData": [{
            "sample": "strainA",
            "data": {
                "sparkline": 23123,
                "otherplot": [1,2,3]
             }
        }],
    }
```

### Warnings and fails

Data for fails and warnings can be attached to tables:

```
    "reportJson": {

        "warnings": [{
            "sample": "strainA",
            "table": "qc",
            "value": ["warningA", "warningB"]
        }],

        "fails": [{
            "sample": "strainA",
            "table": "qc",
            "value": ["FailA"]
        }]
    }
```

These are the main types of report data that are usually sent to the reports app. However, there are no limitations to other types of data as long as they are correctly parsed in the reports web app.

If you have changes or additional comments, feel free.

**Comment by bfrgoncalves** [comment]
Need to check for back compatibility with reports used in the INNUENDO Platform. If needed, current version of the INNUENDO reports should be updated to a new version that can accommodate this changes in order for a more flexible incorporation of future processes and possibly allow retrieval of reports for multiple samples simultaneously.

**Comment by bfrgoncalves** [comment]
Need also to specify and verify the structure for the typing reports. Currently they are as below:

`"reportJson": {
        "task": "",
        "trace": [],
        "typing": {},
        "versions": [],
        "workdir": ""
   }`

Should we also extend it to have multiple strains typed with the same process?
