### ISSUE TITLE
Return Component Parameters

### ISSUE THREAD

**Issue by bfrgoncalves** [assemblerflow/flowcraft#99]
An option that returns a component available parameters and their default values should be implemented in order to provide to the user information on what parameters they can change.

Possible return JSON object below
`
{
"component_name": [{
name: parameters_name, 
description:parameter_description, 
default: parameter_default }
]
`

**Comment by ODiogoSilva** [comment]
This feautre has been implmeneted with the following JSON format:

```
{
  "componentA": {"paramA": {"default": "A", "description": "B"}, "paramB": { ... }}
  "componentB": { ... }
}
```
